In [9]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score


In [12]:
df1 = pd.read_csv("spam.csv", encoding='latin1')


In [ ]:
df1

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [16]:
df1['v1'] = df1.v1.map({'ham':0, 'spam':1})
df1

v1                                                 v2 Unnamed: 2  \
0      0  Gountiljurongpoint,crazy..Availableonlyinbugis...        NaN   
1      0                           Oklar...Jokingwifuoni...        NaN   
2      1  Freeentryin2awklycomptowinFACupfinaltkts21stMa...        NaN   
3      0            Udunsaysoearlyhor...Ucalreadythensay...        NaN   
4      0  NahIdon'tthinkhegoestousf,helivesaroundherethough        NaN   
...   ..                                                ...        ...   
5508   1  This is the 2nd time we have tried 2 contact u...        NaN   
5509   0              Will Ì_ b going to esplanade fr home?        NaN   
5510   0  Pity, * was in mood for that. So...any other s...        NaN   
5511   0  The guy did some bitching but I acted like i'd...        NaN   
5512   0                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5508        NaN        NaN  
5509        NaN        NaN  
5510        NaN        NaN  
5511        NaN        NaN  
5512        NaN        NaN  

[5513 rows x 5 columns]

In [17]:
X= df1['v2'].to_numpy()
Y = df1['v1'].to_numpy()
Y = Y.astype('int')


In [18]:
print("X")
print(X)
print("y")
print(Y)

X
['Gountiljurongpoint,crazy..Availableonlyinbugisngreatworldlaebuffet...Cinetheregotamorewat...'
 'Oklar...Jokingwifuoni...'
 "Freeentryin2awklycomptowinFACupfinaltkts21stMay2005.TextFAto87121toreceiveentryquestion(stdtxtrate)T&Csapply08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
y
[0 0 1 ... 0 0 0]


In [19]:
vec = CountVectorizer( )

In [20]:
vec.fit(X)
vec.vocabulary_

{'gountiljurongpoint': 3605,
 'crazy': 2329,
 'availableonlyinbugisngreatworldlaebuffet': 1305,
 'cinetheregotamorewat': 2048,
 'oklar': 5518,
 'jokingwifuoni': 4323,
 'freeentryin2awklycomptowinfacupfinaltkts21stmay2005': 3364,
 'textfato87121toreceiveentryquestion': 7602,
 'stdtxtrate': 7232,
 'csapply08452810075over18': 2362,
 'udunsaysoearlyhor': 7966,
 'ucalreadythensay': 7964,
 'nahidon': 5245,
 'tthinkhegoestousf': 7910,
 'helivesaroundherethough': 3816,
 'freemsgheytheredarlingit': 3369,
 'sbeen3week': 6640,
 'snowandnowordback': 7021,
 'dlikesomefunyouupforitstill': 2674,
 'tbok': 7528,
 'xxxstdchgstosend': 8569,
 '50torcv': 624,
 'evenmybrotherisnotliketospeakwithme': 3005,
 'theytreatmelikeaidspatent': 7658,
 'asperyourrequest': 1244,
 'mellemelle': 4971,
 'oruminnaminungintenurunguvettam': 5601,
 'hasbeensetasyourcallertuneforallcallers': 3761,
 'press': 6044,
 '9tocopyyourfriendscallertune': 843,
 'winner': 8428,
 'asavaluednetworkcustomeryouhavebeenselectedtoreceiveaå': 1

In [21]:
vec = CountVectorizer(stop_words='english')
vec.fit(X)
vec.vocabulary_

{'gountiljurongpoint': 3505,
 'crazy': 2273,
 'availableonlyinbugisngreatworldlaebuffet': 1273,
 'cinetheregotamorewat': 1994,
 'oklar': 5357,
 'jokingwifuoni': 4197,
 'freeentryin2awklycomptowinfacupfinaltkts21stmay2005': 3271,
 'textfato87121toreceiveentryquestion': 7395,
 'stdtxtrate': 7030,
 'csapply08452810075over18': 2305,
 'udunsaysoearlyhor': 7734,
 'ucalreadythensay': 7732,
 'nahidon': 5099,
 'tthinkhegoestousf': 7681,
 'helivesaroundherethough': 3711,
 'freemsgheytheredarlingit': 3276,
 'sbeen3week': 6457,
 'snowandnowordback': 6826,
 'dlikesomefunyouupforitstill': 2614,
 'tbok': 7322,
 'xxxstdchgstosend': 8306,
 '50torcv': 624,
 'evenmybrotherisnotliketospeakwithme': 2929,
 'theytreatmelikeaidspatent': 7442,
 'asperyourrequest': 1213,
 'mellemelle': 4835,
 'oruminnaminungintenurunguvettam': 5434,
 'hasbeensetasyourcallertuneforallcallers': 3659,
 'press': 5865,
 '9tocopyyourfriendscallertune': 843,
 'winner': 8169,
 'asavaluednetworkcustomeryouhavebeenselectedtoreceiveaå': 1

In [22]:

print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['00' '000' '000pes' ... 'ûïharry' 'ûò' 'ûówell']
8420


In [23]:
X_transformed=vec.transform(X)
X_transformed

<5513x8420 sparse matrix of type '<class 'numpy.int64'>'
	with 42911 stored elements in Compressed Sparse Row format>

In [24]:
X=X_transformed.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

00  000  000pes  000poundstxt  000prizejackpot  008704050406  0089  \
0      0    0       0             0                0             0     0   
1      0    0       0             0                0             0     0   
2      0    0       0             0                0             0     0   
3      0    0       0             0                0             0     0   
4      0    0       0             0                0             0     0   
...   ..  ...     ...           ...              ...           ...   ...   
5508   0    0       0             0                0             0     0   
5509   0    0       0             0                0             0     0   
5510   0    0       0             0                0             0     0   
5511   0    0       0             0                0             0     0   
5512   0    0       0             0                0             0     0   

      0121  01223585236  01223585334  ...  ó_  û_  û_thanks  ûªm  ûªt  ûªve  \
0        0            0            0  ...   0   0         0    0    0     0   
1        0            0            0  ...   0   0         0    0    0     0   
2        0            0            0  ...   0   0         0    0    0     0   
3        0            0            0  ...   0   0         0    0    0     0   
4        0            0            0  ...   0   0         0    0    0     0   
...    ...          ...          ...  ...  ..  ..       ...  ...  ...   ...   
5508     0            0            0  ...   0   0         0    0    0     0   
5509     0            0            0  ...   0   0         0    0    0     0   
5510     0            0            0  ...   0   0         0    0    0     0   
5511     0            0            0  ...   0   0         0    0    0     0   
5512     0            0            0  ...   0   0         0    0    0     0   

      ûï  ûïharry  ûò  ûówell  
0      0        0   0       0  
1      0        0   0       0  
2      0        0   0       0  
3      0        0   0       0  
4      0        0   0       0  
...   ..      ...  ..     ...  
5508   0        0   0       0  
5509   0        0   0       0  
5510   0        0   0       0  
5511   0        0   0       0  
5512   0        0   0       0  

[5513 rows x 8420 columns]

In [26]:
df2 = pd.read_csv("spam.csv", encoding='latin1') 
df2
from sklearn.preprocessing import LabelEncoder

In [27]:
test_numpy_array = df2.values
X_test = test_numpy_array[:, 0]
y_test = test_numpy_array[:, 1]
label_encoder = LabelEncoder()
y_test = label_encoder.fit_transform(y_test)

print("X_test:")
print(X_test)
print("y_test:")
print(y_test)


X_test:
['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']
y_test:
[1142 3165 1005 ... 3255 3864 3377]


In [28]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<5513x8420 sparse matrix of type '<class 'numpy.int64'>'
	with 5513 stored elements in Compressed Sparse Row format>

In [29]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
mnb=MultinomialNB()

mnb.fit(X,Y)

mnb.predict_proba(X_test)

array([[0.9394159, 0.0605841],
       [0.9394159, 0.0605841],
       [0.6079351, 0.3920649],
       ...,
       [0.9394159, 0.0605841],
       [0.9394159, 0.0605841],
       [0.9394159, 0.0605841]])

In [31]:
y_prediction = mnb.predict(X_test)


acc = accuracy_score(y_test, y_prediction)


print("Accuracy:", acc)


Accuracy: 0.00018138944313440957
